site_name: Broker IoT
site_description: Broker IoT
site_author: Renato Ribas
site_url: https://github.com/RenatoRibas/Design-Patterns-for-IoT-Embedded-Systems.git

theme: readthedocs

nav:
  - Home: index.md
  - API Reference: apidoc.md
  - Settings: settings.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
extra_css:
  - docs/css/styles.css
