sonar.projectKey=Design-Patterns-for-IoT-Embedded-Systems
sonar.projectName=Design-Patterns-for-IoT-Embedded-Systems
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.token=sqp_dcd36ec1c1b3ae3cddad6aaf657eb1c2feca963a
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12